modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "remorphed"
version = "${version}"
displayName = "ReMorphed"
authors = "To_Craft"
description = '''
Transform like in the old-school morph mod!
'''
#logoFile = ""

[[dependencies.remorphed]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.remorphed]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.remorphed]]
modId = "craftedcore"
mandatory = true
versionRange = "[${craftedcore_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.remorphed]]
modId = "walkers"
mandatory = true
versionRange = "[${woodwalkers_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.remorphed]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"