modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "remorphed"
version = "${version}"
displayName = "ReMorphed"
authors = "To_Craft"
description = '''
Transform like in the old-school morph mod!
'''
#logoFile = ""

[[dependencies.remorphed]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.remorphed]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.remorphed]]
modId = "craftedcore"
mandatory = true
versionRange = "[1.1,)"
ordering = "AFTER"
side = "BOTH"