org.gradle.jvmargs=-Xmx4G
# Base Versions
modid=remorphed
artifact_type=release
mod_version=8.1
maven_group=dev.tocraft
# Loader Versions
fabric_loader=0.19.3
neoform_version=26.2-2
mixinextras_version=0.5.4
# Upload data
curseforge_id=950721
modrinth_id=8aeV5uJW
required_dependencies=woodwalkers,crafted-core
optional_dependencies=skinshifter
# Discord Webhook
ping_role=1247931121019261070
# <--- ModMaster --->
minecraft=26.2
supported_versions=26.2
java=25
fabric=0.157.0+26.2
neoforge=26.2.0.59
# Dependencies
craftedcore_version=8.2.1
woodwalkers_version=8.3
skinshifter_version=3.2.0
