#file: noinspection YAMLSchemaValidation
blank_issues_enabled: true
contact_links:
  - name: ToCraft's Mods Discord
    url: https://discord.gg/Y3KqxWDUYy
    about: Join for personal support and access to the community.