modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mixins]]
config = "remorphed.mixins.json"

[[mods]]
modId = "remorphed"
version = "${version}"
displayName = "ReMorphed"
authors = "To_Craft"
description = '''
Transform like in the old-school morph mod!
'''
#logoFile = ""

[[dependencies.remorphed]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.remorphed]]
modId = "craftedcore"
mandatory = true
versionRange = "[1.1,)"
ordering = "AFTER"
side = "BOTH"